# Generated by Django 4.1.7 on 2023-02-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Account type')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Crew name')),
                ('job_title', models.CharField(max_length=100, verbose_name='\tJob Title')),
                ('assignment', models.CharField(max_length=255, verbose_name='Work Assignment')),
                ('details', models.TextField(verbose_name='Assignment Details')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crew_account', to='reservation.accounts', verbose_name='Account')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer name')),
                ('age', models.PositiveIntegerField(verbose_name='Customer age')),
                ('gender', models.BooleanField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', verbose_name='Customer gender')),
                ('contact_number', models.CharField(max_length=100, verbose_name='Customer phone number')),
                ('address', models.TextField(verbose_name='Customer address')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='reservation.accounts', verbose_name='Account')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=150, verbose_name='Payment method')),
                ('amount', models.PositiveIntegerField(verbose_name='Payment amount')),
                ('date', models.DateTimeField(verbose_name='Date of Payment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='reservation.customers', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date of Reservation')),
                ('date_in', models.DateTimeField(verbose_name='Date of Coming In')),
                ('date_out', models.DateTimeField(verbose_name='Date of Coming Out')),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Payment')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_reservation', to='reservation.crew', verbose_name='Crew')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reservation', to='reservation.customers', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Room type name')),
                ('description', models.TextField(verbose_name='Room type description')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(verbose_name='Transaction date')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_transaction', to='reservation.crew', verbose_name='Crew')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transaction', to='reservation.customers', verbose_name='Customer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='reservation.payment', verbose_name='Payment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_transaction', to='reservation.reservation', verbose_name='Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Room name')),
                ('description', models.TextField(verbose_name='Room description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Room price')),
                ('status', models.CharField(max_length=100, verbose_name='Room status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='reservation.roomtype', verbose_name='Room type')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservation', to='reservation.rooms', verbose_name='Room'),
        ),
    ]
